---
version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    environment:
      - ENV_PATH=../../../.env
      - CORE_API_ROOT=https://platform-staging.raceatyourpace.browserhosting.com/api
      - WEB_ROOT_URI=https://localhost:3001
      - APP_PROTOCOL=rap://app
      - AWS_REGION=eu-west-2
      - COGNITO_USER_POOL_ID=eu-west-2_58RzDPnHP
      - COGNITO_USER_POOL_WEB_ID=kr80f01i2s2e81dk8i1bcvpaq
      - COGNITO_AUTH_BASE=raceatyourpace-staging.auth.eu-west-2.amazoncognito.com
      - AWS_CLIENT_ID=kr80f01i2s2e81dk8i1bcvpaq
      - AWS_CLIENT_SECRET=d7m7lf5o618922444d693s3g4f34804hvciaupjd419lh3htid1
      - COOKIE_SIGNING_KEY=CgJjeUT6Haf3exhxZsPX4EsXmBriTxQoJ4fjL88ZG2ogt5ncpKuFeRaFY5BxhTzUA9VXzLYiK6kEwhaztTLmSjpMEHuXwvx7wedfpLDtEA9rmaE7RcE3aPbRGNN9UzqA
      - BUGSNAG_API_KEY=f87a66b2ed5b9bf5b0d8c5389c47d989
